### ISSUE TITLE
GPS loads only 1 geocache from the generated GPX file

### ISSUE THREAD

**Issue by yohhaan** [Surfoo/unpublished-geocaches#7]
Hello Surfoo, 

Here is an issue that I faced today: 

# Description
I generated a GPX file of several unpublished geocaches and transferred it to my GPS. However, only the 1st geocache from the file was loaded and not the other ones.

# Steps to reproduce
1. Generate a GPX file for several unpublished geocaches
2. Transfer the GPX file to your GPS (does not work at least on the Garmin Dakota 20)
3. Power on the GPS, search for the geocaches in the GPX file: only the first geocache of the file is present and displayed, the other ones are not loaded. 

# Origin of the issue
Looking into the GPX file and comparing it with the one generated by the Geocaching website on a published geocache, I figured out that the problem was with the `id` value of the following XML tag (in the template `waypoint.xml`): `<groundspeak:cache id="{{ referenceCode }}" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">`. 

This web app uses the GC code (base 31)  of the geocache whereas the Geocaching website uses the unique id (base 16). The GPS fails because of that to load the whole list of geocaches from the GPX file: when I changed the ids of my generated GPX file for a base 16 id, the caches were loaded by the GPS. So, converting the `referenceCode` attribute before setting it to be the value of this `id` should fix this issue. 

Thanks a lot for this useful web app!
Regards,

yohhaan

**Comment by Surfoo** [comment]
Hello yohhaan, 

Thanks for your great bug report ! I just fixed this very old bug on the app :)

**Comment by yohhaan** [comment]
Thanks a lot! The bug is now fixed and the issue can be closed.
